version: 2.1

executors:
  docker-executor:
    docker:
      - image: openjdk:17-jdk

jobs:
  build_and_push:
    executor: docker-executor
    steps:
      - checkout

      - run:
          name: Build with Maven
          command: mvn clean package

      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true

      - run:
          name: Configure AWS CLI
          command: |
            echo "[default]" > ~/.aws/config
            echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ~/.aws/config
            echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/config
            echo "region = us-east-2" >> ~/.aws/config

      - run:
          name: Log in to Amazon ECR
          command: |
            aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com

      - run:
          name: Build Docker image
          command: docker build -t java-mongo .

      - run:
          name: Tag Docker image
          command: docker tag java-mongo:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/${{ secrets.REPOSITORY_NAME }}:latest

      - run:
          name: Push Docker image to ECR
          command: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/${{ secrets.REPOSITORY_NAME }}:latest

workflows:
  version: 2
  build_and_push_workflow:
    jobs:
      - build_and_push
